---
- hosts: mgmt

  vars:
    http_root_directory: /opt/httproot
    tftp_root_directory: /opt/tftproot

  roles:
    - role: bennojoy.nginx
      nginx_http_params: {sendfile: "on", access_log: "/var/log/nginx/access.log"}
      nginx_sites:
       - server:
          file_name: mgmt
          listen: 80
          server_name: localhost
          root: "{{ http_root_directory }}"
          location1: {name: /, try_files: "$uri $uri/ /index.html"}

    - role: bertvv.tftp

  tasks:
    - name: Make a test file in the http directory
      copy:
        content: HTTP Hello world!
        dest: "{{ http_root_directory }}/test_http.txt"
        owner: nginx
        group: nginx
        mode: 0644
    - name: Make a test file in the tftp directory
      copy:
        content: TFTP Hello world!
        dest: "{{ tftp_root_directory }}/test_tftp.txt"
        owner: root
        group: root
        mode: 0644
